"""New species built on the pack's existing models: region, base model, size, behaviour and a color recipe.

Each entry: id -> dict(
  name, region, base (an existing animal id), group (roster group), role, prey, humans, dmg, tame,
  scale (render + hitbox), recipe (see recolor.py; "bones" paints whole body parts, e.g. a white head),
  geo (optional shape tweaks: {"scale_bones": {bone: [x, y, z]}, "hide": [bones]}))
"""
from animals import SMALL, MID, BIG, FISH, MARINE

# ramps: dark -> light
BROWN = ["#1d130c", "#3b2819", "#5c4129", "#82603f", "#a98762"]
DARK_BROWN = ["#140d08", "#2a1b11", "#40291a", "#5b3d27", "#7d5a3d"]
REDDISH = ["#2a120a", "#5e2a14", "#8c4421", "#b46738", "#d9a578"]
TAWNY = ["#3a2410", "#7a5226", "#a87a3e", "#cba567", "#ead7b0"]
SANDY = ["#4a3a26", "#8a7250", "#b39d74", "#d4c39e", "#efe6cf"]
GREY = ["#1e1e1f", "#3e3e40", "#626264", "#8c8c8e", "#bcbcbc"]
GREY_BROWN = ["#24201b", "#47403a", "#6c625a", "#958a7f", "#c3b9ac"]
BLACK = ["#08080a", "#141416", "#222226", "#34343a", "#4c4c54"]
WHITE = ["#7a7a7a", "#a8a8a6", "#cfcfcb", "#e9e9e4", "#fbfbf8"]
OLIVE = ["#141a0e", "#2c3520", "#485335", "#6a7550", "#97a07a"]
GOLD = ["#3a2408", "#8a5814", "#c4862a", "#e0b058", "#f6e3b4"]
ORANGE_TIGER = ["#2a1306", "#8a3c0e", "#c96318", "#e59a48", "#f7e8d4"]

S = {
    # ================= North America (USA, Canada, Mexico)
    "moose": dict(name="Moose", region="Canada, USA, Russia, Northern Europe", base="deer", group="deer", role="defensive",
                  dmg=8, tame="minecraft:wheat", scale=1.6,
                  recipe=dict(ramp=["#140d09", "#2a1d14", "#3f2c1f", "#5a432f", "#7f6a52"], lift=0.06,
                              bones={("leg",): ["#3a2e24", "#5e4c3c", "#8a7660", "#a8967e", "#c8b8a0"],
                                     ("cuernos", "cuerno"): ["#5a4632", "#8a7254", "#b09a78", "#cdbb98", "#e2d6bc"]}),
                  geo={"hide": ["cuerno0", "cuerno1"],
                       "scale_bones": {"cabeza": [1.2, 1.15, 1.45], "body": [1.15, 1.15, 1.0]},
                       "add": [{"bone": "cuernos", "origin": [2.2, 29.6, -6.5], "size": [6, 1, 5], "rotation": [0, 0, -18], "pivot": [1.0, 29.6, -4]},
                               {"bone": "cuernos", "origin": [7.6, 30.4, -6.3], "size": [1, 2, 1], "rotation": [0, 0, -18], "pivot": [1.0, 29.6, -4]},
                               {"bone": "cuernos", "origin": [7.6, 30.4, -4.6], "size": [1, 2, 1], "rotation": [0, 0, -18], "pivot": [1.0, 29.6, -4]},
                               {"bone": "cuernos", "origin": [7.6, 30.4, -2.9], "size": [1, 2, 1], "rotation": [0, 0, -18], "pivot": [1.0, 29.6, -4]},
                               {"bone": "cuernos", "origin": [-8.2, 29.6, -6.5], "size": [6, 1, 5], "rotation": [0, 0, 18], "pivot": [-1.0, 29.6, -4]},
                               {"bone": "cuernos", "origin": [-8.6, 30.4, -6.3], "size": [1, 2, 1], "rotation": [0, 0, 18], "pivot": [-1.0, 29.6, -4]},
                               {"bone": "cuernos", "origin": [-8.6, 30.4, -4.6], "size": [1, 2, 1], "rotation": [0, 0, 18], "pivot": [-1.0, 29.6, -4]},
                               {"bone": "cuernos", "origin": [-8.6, 30.4, -2.9], "size": [1, 2, 1], "rotation": [0, 0, 18], "pivot": [-1.0, 29.6, -4]},
                               {"bone": "cabeza", "origin": [-0.5, 19.5, -8.5], "size": [1, 3, 2], "uv": [29, 16]}]}),
    "elk": dict(name="Elk", region="USA, Canada", base="deer", group="deer", role="defensive", dmg=6, tame="minecraft:wheat",
                scale=1.3, recipe=dict(ramp=TAWNY, bones={("head", "cabeza", "boca"): DARK_BROWN},
                                       contrast=1.05),
                geo={"scale_bones": {"cuernos": [1.3, 1.25, 1.3]}}),
    "caribou": dict(name="Caribou (Reindeer)", region="Canada, Russia, Northern Europe", base="deer", group="deer",
                    role="defensive", dmg=5, tame="minecraft:wheat", scale=1.15,
                    recipe=dict(ramp=["#2b2622", "#544b43", "#7f7468", "#aca294", "#e4ded2"],
                                bones={("head", "cabeza"): ["#6b6258", "#9c9182", "#c9c0b2", "#e4ded2", "#f6f3ec"]})),
    "american_bison": dict(name="American Bison", region="USA, Canada", base="buffalo", group="cattle", role="defensive",
                           dmg=8, tame="minecraft:wheat", scale=1.15,
                           recipe=dict(ramp=["#140c07", "#2e1d12", "#4a301e", "#6e4c30", "#8e6c4a"], lift=0.12)),
    "grizzly_bear": dict(name="Grizzly Bear", region="USA, Canada", base="bear", group="bears", role="apex",
                         prey=["fish", "deer", "elk", "moose", "caribou", "wild_boar", "rabbit"], humans=8, dmg=8,
                         tame="minecraft:salmon", scale=1.15,
                         recipe=dict(ramp=["#1c120b", "#3d2a1c", "#6a4d34", "#9a7c5c", "#c8b090"],
                                     pattern=[{"type": "speckle", "color": "#d2bd98", "density": 0.06, "size": 0.6,
                                               "opacity": 0.55}])),
    "coyote": dict(name="Coyote", region="USA, Mexico, Canada", dog=True, group="wild_canids", role="hunter",
                   prey=SMALL, dmg=3, tame="minecraft:chicken", breed="coyote"),
    "bobcat": dict(name="Bobcat", region="USA, Mexico", base="caracal", group="wild_cats", role="hunter", prey=SMALL,
                   dmg=4, tame="minecraft:chicken", scale=0.95,
                   recipe=dict(ramp=["#2a1d12", "#6b4e33", "#9a7a56", "#c4a984", "#eadfcb"],
                               pattern=[{"type": "spots", "color": "#24170e", "density": 0.02, "size": 0.55,
                                         "max_t": 0.85}])),
    "canada_lynx": dict(name="Canada Lynx", region="Canada, USA", base="caracal", group="wild_cats", role="hunter",
                        prey=SMALL, dmg=4, tame="minecraft:rabbit", scale=1.05,
                        recipe=dict(ramp=["#26221e", "#58504a", "#857c72", "#b2aa9e", "#e0dbd2"],
                                    pattern=[{"type": "speckle", "color": "#2d2722", "density": 0.05, "size": 0.6,
                                              "max_t": 0.8}])),
    "jaguar": dict(name="Jaguar", region="Mexico, Central & South America", base="leopard", group="big_cats", role="apex",
                   prey=SMALL + MID + ["javelina", "american_crocodile"], humans=9, dmg=8, tame="minecraft:beef",
                   scale=1.1, recipe=dict(ramp=["#24170a", "#9a6120", "#d4952e", "#e8b860", "#f4e6c8"], contrast=1.1)),
    "bald_eagle": dict(name="Bald Eagle", region="USA, Canada", base="eagle", group="birds_of_prey", role="hunter",
                       prey=["rabbit", "fish", "squirrel", "rat"], dmg=4, tame="minecraft:salmon", scale=1.05,
                       recipe=dict(ramp=["#140d08", "#2e2015", "#46321f", "#5e4630", "#7a6048"],
                                   bones={("head", "cabeza", "cabeza0", "tail"): WHITE,
                                          ("pico", "dedo", "leg0_", "leg1"): GOLD})),
    "american_alligator": dict(name="American Alligator", region="USA", base="crocodile", group="crocodilians",
                               role="apex", prey=MID + FISH + ["raccoon", "turtle"], humans=10, dmg=8,
                               tame="minecraft:chicken", scale=1.05,
                               recipe=dict(ramp=["#090b07", "#171c12", "#262e1e", "#3a442f", "#68705a"])),
    "american_crocodile": dict(name="American Crocodile", region="Dominican Republic, Mexico, USA", base="crocodile",
                               group="crocodilians", role="apex", prey=MID + FISH, humans=10, dmg=8,
                               tame="minecraft:chicken", scale=1.0,
                               recipe=dict(ramp=["#1a1c10", "#3a3e24", "#5c6238", "#868a58", "#c4c098"])),
    "rattlesnake": dict(name="Rattlesnake", region="USA, Mexico", base="snake", group="snakes", role="apex", prey=SMALL,
                        humans=4, dmg=4, tame="minecraft:rabbit", scale=1.0,
                        recipe=dict(ramp=["#2a1f14", "#5a4630", "#8c7452", "#b49c76", "#d8c8a6"],
                                    pattern=[{"type": "bands", "color": "#3a2a1a", "period": 5, "width": 0.4,
                                              "axis": "y", "max_t": 0.9}])),
    "gila_monster": dict(name="Gila Monster", region="USA, Mexico", base="iguana", group="lizards", role="defensive",
                         dmg=3, tame="minecraft:egg", scale=0.75,
                         recipe=dict(ramp=["#0c0a0a", "#1e1816", "#2e2420", "#3a2e28", "#4a3a32"],
                                     pattern=[{"type": "spots", "color": "#e07a3a", "density": 0.05, "size": 0.9}])),
    "skunk": dict(name="Skunk", region="USA, Canada, Mexico", base="raccoon", group="small_mammals", role="defensive",
                  dmg=1, tame="minecraft:sweet_berries", scale=0.85,
                  recipe=dict(ramp=BLACK, bones={("tail",): WHITE},
                              pattern=[{"type": "bands", "color": "#efefea", "period": 16, "width": 0.18,
                                        "axis": "x", "area": (0.0, 0.0, 1.0, 0.5)}])),
    "beaver": dict(name="Beaver", region="Canada, USA, Northern Europe", base="raccoon", group="small_mammals",
                   role="passive", tame="minecraft:apple", scale=1.0,
                   recipe=dict(ramp=["#1a100a", "#3a2416", "#5a3a24", "#7a5436", "#9a7454"])),
    "opossum": dict(name="Opossum (Tlacuache)", region="Mexico, USA", base="rat", group="small_mammals", role="passive",
                    tame="minecraft:egg", scale=1.6,
                    recipe=dict(ramp=["#2a2a2a", "#5c5a58", "#8e8a86", "#c2beb8", "#f2f0ea"],
                                bones={("head",): WHITE})),
    "porcupine": dict(name="Porcupine", region="USA, Canada", base="erizo", group="small_mammals", role="defensive",
                      dmg=3, tame="minecraft:apple", scale=1.5,
                      recipe=dict(ramp=["#140f0b", "#2c221a", "#4a3a2c", "#8a7864", "#d8ccb8"])),
    "beluga": dict(name="Beluga Whale", region="Canada, Russia, Arctic", base="orca", group="whales", role="passive",
                   tame="minecraft:cod", scale=0.8, recipe=dict(ramp=WHITE, contrast=0.8)),
    "humpback_whale": dict(name="Humpback Whale", region="Dominican Republic, Mexico, Canada", base="ballena",
                           group="whales", role="passive", tame="minecraft:cod", scale=1.1,
                           recipe=dict(ramp=["#0a0c10", "#1a1e26", "#2c323c", "#4a525e", "#c8ccd0"])),
    "manatee": dict(name="Manatee", region="Dominican Republic, Mexico, USA", base="seal", group="whales",
                    role="passive", tame="minecraft:seagrass", scale=1.7,
                    recipe=dict(ramp=["#2a2a28", "#4a4a46", "#6a6a64", "#8a8a82", "#aaa9a0"], contrast=0.8)),
    # ================= Dominican Republic / Caribbean
    "rhinoceros_iguana": dict(name="Rhinoceros Iguana", region="Dominican Republic, Haiti", base="iguana",
                              group="lizards", role="defensive", dmg=2, tame="minecraft:sweet_berries", scale=1.25,
                              recipe=dict(ramp=["#1a1c1e", "#3a3e40", "#5c6062", "#82868a", "#aeb2b2"])),
    "solenodon": dict(name="Hispaniolan Solenodon", region="Dominican Republic, Haiti", base="rat",
                      group="small_mammals", role="defensive", dmg=2, tame="minecraft:spider_eye", scale=1.35,
                      recipe=dict(ramp=["#1e120a", "#4a2c18", "#7a4c2c", "#a87448", "#d8b08a"])),
    "palmchat": dict(name="Palmchat", region="Dominican Republic (national bird)", base="dove", group="songbirds",
                     role="passive", tame="minecraft:sweet_berries", scale=0.8,
                     recipe=dict(ramp=["#1e1a10", "#3e3a24", "#5e5a3a", "#8a8458", "#c8c2a0"],
                                 pattern=[{"type": "stripes", "color": "#3a2e1e", "period": 3, "width": 0.3,
                                           "axis": "x", "wobble": 0.3, "max_t": 0.95}])),
    # ================= Europe (Italy, Greece, Northern Europe)
    "red_deer": dict(name="Red Deer", region="Italy, Northern Europe, Russia", base="deer", group="deer",
                     role="defensive", dmg=4, tame="minecraft:apple", scale=1.15, recipe=dict(ramp=REDDISH),
                     geo={"scale_bones": {"cuernos": [1.2, 1.2, 1.2]}}),
    "fallow_deer": dict(name="Fallow Deer", region="Italy, Greece, Europe", base="deer", group="deer", role="passive",
                        tame="minecraft:apple", scale=0.9,
                        recipe=dict(ramp=["#2a140a", "#6a3418", "#9a5428", "#c48450", "#efd8bc"],
                                    pattern=[{"type": "spots", "color": "#f1e6d2", "density": 0.05, "size": 0.45}]),
                        geo={"scale_bones": {"cuernos": [1.4, 0.8, 1.4]}}),
    "sika_deer": dict(name="Sika Deer", region="Korea, Russia, Japan", base="deer", group="deer", role="passive",
                      tame="minecraft:apple", scale=0.85,
                      recipe=dict(ramp=["#1e140c", "#4a3220", "#6e4c32", "#946e4c", "#d8c8b0"],
                                  pattern=[{"type": "spots", "color": "#e8dcc6", "density": 0.045, "size": 0.4,
                                            "opacity": 0.85}])),
    "wisent": dict(name="European Bison (Wisent)", region="Poland, Northern Europe, Russia", base="buffalo",
                   group="cattle", role="defensive", dmg=8, tame="minecraft:wheat", scale=1.1,
                   recipe=dict(ramp=["#1a0f08", "#3a2414", "#5a3a22", "#7e5634", "#a07850"], lift=0.1)),
    "eurasian_lynx": dict(name="Eurasian Lynx", region="Northern Europe, Russia, Mongolia", base="caracal",
                          group="wild_cats", role="hunter", prey=SMALL + ["sika_deer", "roe_deer"], dmg=5,
                          tame="minecraft:rabbit", scale=1.15,
                          recipe=dict(ramp=["#2e2014", "#6e5236", "#9c7c58", "#c6aa86", "#ece2d0"],
                                      pattern=[{"type": "spots", "color": "#2a1c10", "density": 0.022, "size": 0.5,
                                                "max_t": 0.85}])),
    "european_badger": dict(name="European Badger", region="Italy, Greece, Northern Europe, Korea", base="raccoon",
                            group="small_mammals", role="defensive", dmg=3, tame="minecraft:sweet_berries",
                            scale=1.0, recipe=dict(ramp=GREY, bones={("head",): ["#0a0a0a", "#202020", "#e6e6e2",
                                                                                   "#f2f2ee", "#fbfbf8"]})),
    "barn_owl": dict(name="Barn Owl", region="Italy, Greece, worldwide", base="eagle", group="birds_of_prey",
                     role="hunter", prey=["rat", "rabbit", "squirrel"], dmg=2, tame="minecraft:rabbit", scale=0.6,
                     recipe=dict(ramp=["#6a4a26", "#a07440", "#c8a068", "#e8d4b0", "#fbf6ea"],
                                 bones={("head", "cabeza", "cabeza0"): WHITE},
                                 pattern=[{"type": "speckle", "color": "#5a5a5a", "density": 0.05, "size": 0.5,
                                           "opacity": 0.6}])),
    "snowy_owl": dict(name="Snowy Owl", region="Canada, Russia, Northern Europe", base="eagle", group="birds_of_prey",
                      role="hunter", prey=["rabbit", "rat"], dmg=2, tame="minecraft:rabbit", scale=0.65,
                      recipe=dict(ramp=WHITE, pattern=[{"type": "speckle", "color": "#2a2a2a", "density": 0.07,
                                                        "size": 0.5}])),
    "atlantic_puffin": dict(name="Atlantic Puffin", region="Iceland, Norway, Northern Europe, Canada",
                            base="penguin_african", group="seabirds", role="passive", tame="minecraft:cod", scale=0.55,
                            recipe=dict(ramp=["#08080a", "#141418", "#2a2a2e", "#d8d8d4", "#fbfbf8"], lift=0.2)),
    "mute_swan": dict(name="Mute Swan", region="Northern Europe, Russia", base="duck", group="seabirds",
                      role="defensive", dmg=2, tame="minecraft:wheat_seeds", scale=1.6, recipe=dict(ramp=WHITE)),
    "common_pheasant": dict(name="Common Pheasant", region="Korea, Mongolia, Italy, USA", base="turkey",
                            group="game_birds", role="passive", tame="minecraft:wheat_seeds", scale=0.7,
                            recipe=dict(ramp=["#2a1206", "#6a3010", "#a0541e", "#c87e3c", "#e6b47a"],
                                        bones={("head", "cabeza"): ["#081a10", "#103020", "#1c4a32", "#e8e8e4",
                                                                    "#b81e1e"]})),
    "eurasian_magpie": dict(name="Magpie", region="Korea (national bird), Europe", base="dove", group="songbirds",
                            role="passive", tame="minecraft:sweet_berries", scale=1.0,
                            recipe=dict(ramp=["#06060a", "#101624", "#1a2236", "#e2e2de", "#fbfbf8"], contrast=1.3)),
    "monk_seal": dict(name="Mediterranean Monk Seal", region="Greece, Italy, Mediterranean", base="seal",
                      group="whales", role="hunter", prey=FISH, dmg=3, tame="minecraft:cod", scale=1.15,
                      recipe=dict(ramp=["#1e1c1a", "#3e3a36", "#5e5852", "#867e76", "#bab2a6"])),
    "hermann_tortoise": dict(name="Hermann's Tortoise", region="Greece, Italy, Balkans", base="land_turtle",
                             group="lizards", role="passive", tame="minecraft:dandelion", scale=0.7,
                             recipe=dict(ramp=["#14100a", "#3a2c14", "#7a6230", "#b89a52", "#e2cc8a"])),
    # ================= Russia, Mongolia, Korea
    "amur_tiger": dict(name="Amur (Siberian) Tiger", region="Russia, Korea, China", base="tiger", group="big_cats",
                       role="apex", prey=SMALL + MID + BIG + ["sika_deer", "red_deer", "wisent", "moon_bear"],
                       humans=10, dmg=10, tame="minecraft:beef", scale=1.2,
                       recipe=dict(ramp=["#1a0d06", "#7a3812", "#b8642a", "#d89c62", "#f8ece0"], lift=0.06)),
    "amur_leopard": dict(name="Amur Leopard", region="Russia, Korea, China", base="leopard", group="big_cats",
                         role="apex", prey=SMALL + MID + ["sika_deer"], humans=7, dmg=7, tame="minecraft:beef",
                         scale=0.95, recipe=dict(ramp=["#1e140c", "#8a6a3e", "#c4a06a", "#e2c898", "#f8f0e2"],
                                                 contrast=1.15)),
    "moon_bear": dict(name="Asiatic Black Bear (Moon Bear)", region="Korea, Russia, India", base="black_bear",
                      group="bears", role="hunter", prey=["fish", "rabbit", "squirrel"], dmg=6,
                      tame="minecraft:sweet_berries", scale=1.0,
                      recipe=dict(ramp=BLACK, bones={("boca",): ["#4a3a2c", "#7a6650", "#a8947a", "#d4c4ac",
                                                                 "#f0e8dc"]})),
    "przewalski_horse": dict(name="Przewalski's Horse", region="Mongolia", base="zebra", group="horses",
                             role="defensive", dmg=3, tame="minecraft:apple", scale=1.0,
                             recipe=dict(ramp=["#3a2410", "#8a6236", "#b8925e", "#d6b88a", "#efe2c8"], contrast=0.22, lift=0.05,
                                         bones={("leg", "tail", "oreja"): DARK_BROWN})),
    "yak": dict(name="Yak", region="Mongolia, Tibet, India", base="buffalo", group="cattle", role="defensive", dmg=6,
                tame="minecraft:wheat", scale=1.0,
                recipe=dict(ramp=["#0a0807", "#1c1612", "#30261e", "#4a3c30", "#d8d0c4"])),
    "red_crowned_crane": dict(name="Red-crowned Crane", region="Korea, Mongolia, Russia, Japan", base="stork",
                              group="seabirds", role="passive", tame="minecraft:cod", scale=1.15,
                              recipe=dict(ramp=WHITE, bones={("cuello",): BLACK,
                                                             ("cabeza", "head"): ["#a01010", "#c81e1e", "#101010",
                                                                                  "#f0f0ec", "#fbfbf8"]})),
    "mandarin_duck": dict(name="Mandarin Duck", region="Korea, Russia, China", base="duck", group="seabirds",
                          role="passive", tame="minecraft:wheat_seeds", scale=0.8,
                          recipe=dict(ramp=["#2a1408", "#7a3a14", "#c8661e", "#e8a040", "#f6ece0"],
                                      bones={("head", "cabeza"): ["#1a3a2a", "#2c5a46", "#c87a2a", "#f2f0ea",
                                                                  "#fbfbf8"],
                                             ("ala",): ["#1a1430", "#3a2c5a", "#5a4a86", "#c86a2a", "#e8b070"]})),
    "stellers_sea_eagle": dict(name="Steller's Sea Eagle", region="Russia, Korea", base="eagle", group="birds_of_prey",
                               role="hunter", prey=FISH + ["rabbit", "seal"], dmg=5, tame="minecraft:salmon",
                               scale=1.25,
                               recipe=dict(ramp=["#0c0806", "#1c1410", "#2c201a", "#3e2e24", "#544034"],
                                           bones={("tail", "ala0_2", "ala0_4"): WHITE, ("pico",): GOLD})),
    "pallas_cat": dict(name="Pallas's Cat (Manul)", region="Mongolia, Russia", base="caracal", group="wild_cats",
                       role="hunter", prey=["rat", "rabbit", "squirrel"], dmg=3, tame="minecraft:rabbit", scale=0.75,
                       recipe=dict(ramp=["#2e2a26", "#625a52", "#928a80", "#c2bab0", "#ece8e2"],
                                   pattern=[{"type": "bands", "color": "#3a332c", "period": 7, "width": 0.25,
                                             "axis": "y", "max_t": 0.8, "opacity": 0.7}])),
    "raccoon_dog": dict(name="Raccoon Dog", region="Korea, Russia, Japan", base="raccoon", group="small_mammals",
                        role="passive", tame="minecraft:sweet_berries", scale=1.05,
                        recipe=dict(ramp=["#141210", "#3a342c", "#6a5e4e", "#9a8c78", "#c8bca8"])),
    # ================= Middle East
    "arabian_oryx": dict(name="Arabian Oryx", region="Middle East (Oman, Saudi Arabia, Jordan)", base="deer",
                         group="antelopes", role="defensive", dmg=5, tame="minecraft:wheat", scale=1.0,
                         recipe=dict(ramp=["#6e6a62", "#b6b2aa", "#dedad2", "#f0eee8", "#fbfbf8"], lift=0.15,
                                     bones={("cuernos", "cuerno"): BLACK}),
                         geo={"hide": ["cuerno0", "cuerno1"], "horns": {"length": 9.6, "spread": 1.0, "tilt": -15, "splay": 4}}),
    "striped_hyena": dict(name="Striped Hyena", region="Middle East, India, North Africa", base="hyenas",
                          group="wild_canids", role="hunter", prey=SMALL + MID, dmg=5, tame="minecraft:beef",
                          scale=1.0,
                          recipe=dict(ramp=["#1a1814", "#4a463e", "#7e786c", "#ada698", "#d8d2c4"], lift=0.3, contrast=0.4,
                                      pattern=[{"type": "stripes", "color": "#14120e", "period": 6, "width": 0.28,
                                                "axis": "x", "max_t": 0.9}])),
    "fennec_fox": dict(name="Fennec Fox", region="Middle East, North Africa", dog=True, group="wild_canids",
                       role="passive", tame="minecraft:sweet_berries", breed="fennec"),
    "asiatic_lion": dict(name="Asiatic Lion", region="India (Gir), once the Middle East & Greece", base="lion",
                         group="big_cats", role="apex", prey=SMALL + MID + BIG + ["nilgai", "blackbuck", "gaur"],
                         humans=10, dmg=8, tame="minecraft:beef", scale=0.95,
                         recipe=dict(ramp=["#3a2a14", "#8a6a3a", "#b8955e", "#d6bb8a", "#efe2c6"])),
    "dorcas_gazelle": dict(name="Gazelle", region="Middle East, Africa, Mongolia", base="deer", group="antelopes",
                           role="passive", tame="minecraft:wheat", scale=0.75,
                           recipe=dict(ramp=SANDY, pattern=[{"type": "bands", "color": "#5a4028", "period": 40,
                                                             "width": 0.06, "axis": "y", "max_t": 0.95}]),
                           geo={"hide": ["cuerno0", "cuerno1"], "horns": {"length": 5.6, "spread": 0.9, "tilt": -18, "splay": 6}}),
    "saker_falcon": dict(name="Saker Falcon", region="Mongolia (national bird), Middle East", base="eagle",
                         group="birds_of_prey", role="hunter", prey=["rabbit", "dove", "rat", "squirrel"], dmg=3,
                         tame="minecraft:rabbit", scale=0.6,
                         recipe=dict(ramp=["#2a1e14", "#5a4430", "#8a6e50", "#bca07e", "#ece0cc"],
                                     pattern=[{"type": "speckle", "color": "#2a1c10", "density": 0.06, "size": 0.5}])),
    "desert_monitor": dict(name="Desert Monitor", region="Middle East, North Africa, India", base="komodo_dragon",
                           group="lizards", role="hunter", prey=["rat", "rabbit", "chicken"], dmg=4,
                           tame="minecraft:egg", scale=0.6,
                           recipe=dict(ramp=SANDY, pattern=[{"type": "bands", "color": "#4a3a24", "period": 6,
                                                             "width": 0.3, "axis": "y", "max_t": 0.9}])),
    # ================= India
    "indian_rhinoceros": dict(name="Indian Rhinoceros", region="India, Nepal", base="rhinoceros", group="giants",
                              role="defensive", dmg=9, tame="minecraft:wheat", scale=1.0,
                              recipe=dict(ramp=["#2a2622", "#4e4842", "#76706a", "#a0948c", "#c8b4ae"],
                                          contrast=1.15)),
    "king_cobra": dict(name="King Cobra", region="India, Southeast Asia", base="snake", group="snakes", role="apex",
                       prey=SMALL + ["snake", "rattlesnake", "indian_python"], humans=5, dmg=6,
                       tame="minecraft:rabbit", scale=1.45,
                       recipe=dict(ramp=["#14120a", "#34301c", "#56502e", "#7e7646", "#c8be8a"],
                                   pattern=[{"type": "bands", "color": "#d8cc96", "period": 8, "width": 0.12,
                                             "axis": "y"}])),
    "indian_python": dict(name="Indian Python", region="India, Southeast Asia", base="snake", group="snakes",
                          role="hunter", prey=SMALL + ["deer", "sika_deer", "blackbuck"], dmg=5,
                          tame="minecraft:rabbit", scale=1.7,
                          recipe=dict(ramp=["#2a2014", "#6a5434", "#9e8458", "#c8b282", "#e8dcbe"],
                                      pattern=[{"type": "spots", "color": "#3a2a18", "density": 0.04, "size": 1.0,
                                                "max_t": 0.9}])),
    "indian_peafowl": dict(name="Indian Peafowl (Peacock)", region="India (national bird)", base="turkey",
                           group="game_birds", role="passive", tame="minecraft:wheat_seeds", scale=0.9,
                           recipe=dict(ramp=["#06102a", "#0c2a6a", "#1a4aa8", "#2e7ad0", "#7ac0e8"],
                                       bones={("tail",): ["#0a1a0a", "#1a4a1a", "#2e7a2a", "#5ab04a", "#d8c84a"]},
                                       pattern=[{"type": "rosettes", "color": "#1a2a8a", "density": 0.05, "size": 1.3,
                                                 "center": "#e0b030", "area": (0.0, 0.64, 0.72, 1.0)}]),
                           geo={"scale_bones": {"tail": [1.25, 1.35, 1.0]}}),
    "sloth_bear": dict(name="Sloth Bear", region="India, Sri Lanka", base="black_bear", group="bears", role="defensive",
                       dmg=6, tame="minecraft:sweet_berries", scale=0.95,
                       recipe=dict(ramp=["#060606", "#121212", "#1e1c1c", "#2c2a2a", "#4a4646"],
                                   bones={("boca",): ["#6a5a4a", "#9a8a74", "#c8b8a2", "#e2d8c8", "#f4efe6"]})),
    "gaur": dict(name="Gaur (Indian Bison)", region="India, Southeast Asia", base="buffalo", group="cattle",
                 role="defensive", dmg=9, tame="minecraft:wheat", scale=1.2,
                 recipe=dict(ramp=["#0c0806", "#1e140e", "#301f14", "#46301e", "#6a4a30"],
                             bones={("leg",): ["#1e140e", "#3a2a1e", "#d8ccb4", "#ece4d4", "#f8f4ec"]})),
    "nilgai": dict(name="Nilgai (Blue Bull)", region="India, Nepal", base="deer", group="antelopes", role="defensive",
                   dmg=4, tame="minecraft:wheat", scale=1.2,
                   recipe=dict(ramp=["#1a1c22", "#3a3e48", "#5a606c", "#7e8490", "#c8ccd2"]),
                   geo={"hide": ["cuerno0", "cuerno1"], "horns": {"length": 2.4, "spread": 0.9, "tilt": -10, "splay": 4}}),
    "blackbuck": dict(name="Blackbuck", region="India, Nepal", base="deer", group="antelopes", role="passive",
                      tame="minecraft:wheat", scale=0.8,
                      recipe=dict(ramp=["#0a0806", "#1a140e", "#2a2018", "#e8e2d8", "#fbfaf6"], contrast=1.4,
                                  bones={("cuernos", "cuerno"): BLACK}),
                      geo={"hide": ["cuerno0", "cuerno1"], "horns": {"length": 8.0, "spread": 1.0, "tilt": -10, "splay": 14}}),
    "gharial": dict(name="Gharial", region="India, Nepal", base="crocodile", group="crocodilians", role="hunter",
                    prey=FISH, dmg=5, tame="minecraft:cod", scale=1.1,
                    recipe=dict(ramp=["#1e2018", "#3e4232", "#62664e", "#8a8e70", "#bcbe9e"]),
                    geo={"scale_bones": {"head": [0.6, 0.8, 1.6], "boca0": [0.6, 0.8, 1.6], "boca1": [0.6, 0.8, 1.6]}}),
    "rhesus_macaque": dict(name="Rhesus Macaque", region="India, Nepal", base="capuchin_monkeys", group="primates",
                           role="defensive", dmg=2, tame="minecraft:melon_slice", scale=1.0,
                           recipe=dict(ramp=["#3a2a18", "#6e563a", "#9a805c", "#c2aa84", "#e8b8a0"])),
    "dhole": dict(name="Dhole (Asian Wild Dog)", region="India, Korea (historic), Russia", dog=True,
                  group="wild_canids", role="hunter", prey=SMALL + MID, dmg=4, tame="minecraft:beef", breed="dhole"),
    # ================= Africa
    "cheetah": dict(name="Cheetah", region="Africa, Iran", base="leopard", group="big_cats", role="hunter",
                    prey=SMALL + MID + ["impala", "dorcas_gazelle"], dmg=6, tame="minecraft:beef", scale=0.95,
                    recipe=dict(ramp=["#3a2810", "#b88a40", "#d9b06a", "#ead2a0", "#f8f0e0"],
                                pattern=[{"type": "spots", "color": "#16100a", "density": 0.018, "size": 0.55,
                                          "max_t": 0.9}])),
    "african_wild_dog": dict(name="African Wild Dog", region="Africa", dog=True, group="wild_canids", role="hunter",
                             prey=SMALL + MID + ["impala", "dorcas_gazelle", "wildebeest"], dmg=4,
                             tame="minecraft:beef", breed="wild_dog"),
    "wildebeest": dict(name="Wildebeest", region="Africa", base="buffalo", group="cattle", role="defensive", dmg=5,
                       tame="minecraft:wheat", scale=0.95,
                       recipe=dict(ramp=["#14161a", "#30343a", "#4c525a", "#6a727c", "#9aa2ac"],
                                   pattern=[{"type": "stripes", "color": "#141618", "period": 8, "width": 0.18,
                                             "axis": "x", "max_t": 0.9, "opacity": 0.7}])),
    "impala": dict(name="Impala", region="Africa", base="deer", group="antelopes", role="passive",
                   tame="minecraft:wheat", scale=0.85,
                   recipe=dict(ramp=["#3a1c0c", "#7a4220", "#a86636", "#cc9a68", "#f6efe4"]),
                   geo={"hide": ["cuerno0", "cuerno1"], "horns": {"length": 6.4, "spread": 1.1, "tilt": -15, "splay": 16}}),
    "greater_kudu": dict(name="Greater Kudu", region="Africa", base="deer", group="antelopes", role="passive",
                         tame="minecraft:wheat", scale=1.2,
                         recipe=dict(ramp=["#2a241e", "#5a5048", "#827670", "#a89c94", "#d8d2ca"],
                                     pattern=[{"type": "stripes", "color": "#f2eee6", "period": 9, "width": 0.1,
                                               "axis": "x", "wobble": 0.2, "max_t": 0.8}]),
                         geo={"hide": ["cuerno0", "cuerno1"], "horns": {"length": 9.6, "spread": 1.3, "tilt": -18, "splay": 22}}),
    "okapi": dict(name="Okapi", region="Africa (Congo)", base="zebra", group="horses", role="passive",
                  tame="minecraft:apple", scale=1.0,
                  recipe=dict(ramp=["#140808", "#2a1210", "#3e1e18", "#5a2e24", "#7a4234"], contrast=0.5,
                              bones={("leg",): ["#0a0606", "#1e1210", "#e8e2dc", "#f4f0ea", "#fbfaf6"]})),
    "warthog": dict(name="Warthog", region="Africa", base="wild_boar", group="pigs", role="defensive", dmg=4,
                    tame="minecraft:carrot", scale=0.95,
                    recipe=dict(ramp=["#1a1816", "#3a3632", "#5a544e", "#7e766e", "#a49a90"])),
    "meerkat": dict(name="Meerkat", region="Africa", base="squirrel", group="small_mammals", role="passive",
                    tame="minecraft:spider_eye", scale=1.0,
                    recipe=dict(ramp=["#3a2c1c", "#7a6446", "#a8906a", "#cbb898", "#ebe0cc"],
                                pattern=[{"type": "bands", "color": "#5a4630", "period": 6, "width": 0.2,
                                          "axis": "y", "max_t": 0.85, "opacity": 0.45}])),
    "olive_baboon": dict(name="Baboon", region="Africa, Arabian Peninsula", base="chimpanzee", group="primates",
                         role="defensive", dmg=5, tame="minecraft:melon_slice", scale=0.85,
                         recipe=dict(ramp=["#1e1a10", "#46402a", "#6e6644", "#968c64", "#c0b690"])),
    "mandrill": dict(name="Mandrill", region="Africa", base="chimpanzee", group="primates", role="defensive", dmg=5,
                     tame="minecraft:melon_slice", scale=0.85,
                     recipe=dict(ramp=["#141410", "#2e2e22", "#4a4a36", "#6a6a4e", "#b8a888"], lift=0.08)),
    "shoebill": dict(name="Shoebill", region="Africa", base="pelican", group="seabirds", role="hunter", prey=FISH,
                     dmg=3, tame="minecraft:cod", scale=1.0,
                     recipe=dict(ramp=["#1e2228", "#3e4650", "#626c78", "#8a96a2", "#b8c2cc"])),
    "black_mamba": dict(name="Black Mamba", region="Africa", base="snake", group="snakes", role="apex",
                        prey=SMALL, humans=5, dmg=6, tame="minecraft:rabbit", scale=1.35,
                        recipe=dict(ramp=["#141614", "#2e322e", "#4a504a", "#6a726a", "#9aa29a"])),
    "secretary_bird": dict(name="Secretary Bird", region="Africa", base="stork", group="birds_of_prey", role="hunter",
                           prey=["snake", "snake_coral", "black_mamba", "rat"], dmg=4, tame="minecraft:rabbit",
                           scale=1.0,
                           recipe=dict(ramp=["#3a3a3c", "#6a6a6c", "#9a9a9c", "#c8c8c8", "#ecece8"],
                                       bones={("leg", "ala0_2", "ala0_3", "tail"): BLACK,
                                              ("cabeza",): ["#a83a10", "#e0661e", "#c8c8c8", "#ecece8", "#fbfbf8"]})),
    # ================= Seas
    "bull_shark": dict(name="Bull Shark", region="Mexico, Dominican Republic, USA", base="white_shark", group="sharks",
                       role="apex", prey=FISH + ["seal", "turtle"], humans=12, dmg=7, tame="minecraft:cod",
                       scale=0.85, recipe=dict(ramp=["#1a1c1e", "#3a3e42", "#5a6066", "#868c92", "#e8eaea"], lift=0.3)),
    "whale_shark": dict(name="Whale Shark", region="Mexico, India, Middle East seas", base="white_shark",
                        group="sharks", role="passive", tame="minecraft:kelp", scale=2.0,
                        recipe=dict(ramp=["#0a1220", "#18263c", "#283a58", "#3e5276", "#e6eaee"],
                                    lift=0.25, pattern=[{"type": "spots", "color": "#e6eaee", "density": 0.07, "size": 0.9}])),
    "manta_ray": dict(name="Manta Ray", region="Mexico, Dominican Republic, Indian Ocean", base="stingray",
                      group="sharks", role="passive", tame="minecraft:kelp", scale=2.2,
                      recipe=dict(ramp=["#08080a", "#16161a", "#26262c", "#3a3a42", "#eaeaea"], no_features=True)),
}

# one per kind, and only where the base model really fits the animal; the rest stay defined but unbuilt
KEEP = {
    "moose", "american_bison", "cheetah", "pallas_cat", "coyote", "fennec_fox", "saker_falcon",
    "red_crowned_crane", "indian_peafowl", "american_alligator", "hermann_tortoise", "rattlesnake", "king_cobra",
    "skunk", "opossum", "przewalski_horse", "okapi", "warthog", "beluga", "whale_shark", "manta_ray",
}
# built and looked at, but too close to an animal the pack already has
LOOKS_LIKE = {"jaguar": "leopard", "bald_eagle": "eagle", "eurasian_lynx": "caracal", "moon_bear": "black bear",
              "yak": "bison", "snowy_owl": "a white eagle", "atlantic_puffin": "african penguin",
              "mute_swan": "a white duck", "european_badger": "raccoon", "meerkat": "squirrel",
              "olive_baboon": "chimpanzee"}
S = {k: v for k, v in S.items() if k in KEEP}
